<script>
	import Header from '../Header.svelte';
	import Icon from '@iconify/svelte';
	import tippy from 'svelte-tippy';
	import 'tippy.js/dist/tippy.css';

	let tooltipContent = 'Click to copy';

	function copyEmail() {
		navigator.clipboard.writeText('conner.chu@outlook.com');
		tooltipContent = 'Copied!';
		setTimeout(() => {
			tooltipContent = 'Click to copy';
		}, 2000);
	}
</script>

<Header />

<section class="hero is-dark">
	<div class="container">
		<div class="hero-body">
			<p class="title is-3 is-spaced">
				Examining the Growth of Methanotrophic Bacteria Immersed in Extremely Low-Frequency
				Electromagnetic Fields
			</p>
			<p class="subtitle is-5 is-spaced">
				Conner Chu<sup>1</sup>, Richard Hamilton<sup>2</sup>, Marina G. Kalyuzhnaya<sup>3</sup>
			</p>
			<p class="subtitle is-6 is-spaced">
				<sup>1</sup> William Howard Taft Charter High School, Woodland Hills, California
				<br /><sup>2, 3</sup> Department of Biology, San Diego State University, San Diego, California
			</p>
			<a
				href="https://emerginginvestigators.org/articles/examining-the-growth-of-methanotrophic-bacteria-immersed-in-extremely-low-frequency-electromagnetic-fields"
				><u>Read with more detailed graphs on the Journal of Emerging Investigators</u></a
			>
			<br />
			<br />
			<p class="title is-4 is-spaced">Abstract</p>
			<p class="subtitle is-6 is-spaced">
				The demand for natural resources, and consequently greenhouse gas (GHG) emissions, are only
				set to increase in the next several decades. Methane gas, having 80 times more warming power
				than carbon dioxide over a 20 year period, accounts for about 10% of all U.S. GHG emissions
				primarily due to the agriculture and waste management industry. GHGs trap heat in Earth’s
				atmosphere causing rising surface temperatures and sea levels, ocean acidification, and
				extreme weather patterns. <i>Methylomicrobium alcaliphilum 20Z<sup>R</sup></i> is a
				methanotrophic bacterium currently being explored as a means for mitigating these emissions
				and/or production of value-added compounds from wasted sources of methane. Based on related
				studies, we predicted that exposure to low-frequency electromagnetic fields for 5 and 15
				minutes would be a feasible method to increase the growth rates of
				<i>M. alcaliphilum 20Z<sup>R</sup></i>, while 30 minutes would decrease the growth rates. We
				hypothesized that this increase in growth could make this method of catabolizing methane
				more practical given the slow growing nature of methanotrophs in standard conditions.
				However, our data showed that exposure to an electromagnetic field density of 0.1 milliTesla
				(mT) at a frequency of 50 hertz (Hz) for 5, 15, and 30 minutes had no statistically
				significant effects on the growth of <i>M. alcaliphilum 20Z<sup>R</sup></i> when compared to
				the control. The results of this study therefore do not fully support our hypothesis that an
				electromagnetic field can positively impact microbial growth, but future research should be done
				to further solidify and expand upon the data collected.
			</p>
			<p class="title is-4 is-spaced">Introduction</p>
			<p class="subtitle is-6 is-spaced">
				The methane concentration in Earth’s atmosphere has doubled since the Industrial Revolution,
				far exceeding natural levels, and accounts for about 20% of the warming in our planet (1).
				Given that methane is 80 times more potent in terms of heat capture than carbon dioxide, the
				effects that methane has on our environment are only magnified (1). In order to lessen this
				effect, researchers and environmentalists have recently taken particular interest in the use
				of methanotrophs, bacteria that consume methane as their source of energy for metabolism.
				Some byproducts of this unique metabolism can even be used for commercial and industrial
				production to produce biofuels and various chemicals like 2,3-butanediol for use as a
				precursor to plastics and pesticides (2). However, numerous studies have addressed the
				limitations associated with methanotrophic oxidation, including most commonly, the issue of
				slow bacterial growth rate, and thus slow methane uptake (3-5). Extremely low-frequency
				(ELF) electromagnetic fields (EMFs) are a form of non-ionizing, lowenergy, non-thermal
				radiation resulting from the combination of electric fields generated by differences in a
				circuit’s voltage and the magnetic fields generated by current flowing through a conductive
				medium (6-7). Several peer-reviewed studies quantifying the impacts of ELF EMFs on
				biological systems have shown that specific parameters like the frequency, time duration,
				and magnetic flux density (the number of magnetic field vectors passing through a given
				area) can accelerate normal cell potentials, increase the rate of healing, reduce
				inflammation, ameliorate bruising, and promote cell proliferation (8-11). Furthermore, these
				same positive impacts have also been observed on the growth of various types of bacteria
				(12-13). Optical density, used as a tool to quantify such growth, is a logarithmic intensity
				ratio of light absorption by a particular substance. If more light is absorbed, there exists
				a greater density of material as opposed to if less light was absorbed, thereby serving as a
				direct representation of growth over time.
				<br />
				<br />
				One of the most common exposure mechanisms in these studies is the use of the Helmholtz coil,
				which consists of two identical magnetic coils facing parallel to each other with the radius
				of each matching the distance separating them. As current passes through both coils, a uniform
				magnetic field is generated within the center of the structure, creating an ideal area for samples
				to be placed into. The positive characteristics of exposure, along with the well-documented methods
				for the construction and utilization of EMF exposure mechanisms like the Helmholtz coil configuration
				used in our study, show the vast potential for its implementation in a variety of industries
				(14-16).
				<br />
				<br />
				Here, we examine the effects of ELF EMFs on
				<i>Methylomicrobium alcaliphilum 20Z<sup>R</sup></i>, a halotolerant, alkaliphilic, obligate
				methanotrophic, Gram-negative bacterium isolated from moderately saline soda lakes in Tuva
				(Central Asia), with the aim of catalyzing species growth and consequently, methane
				consumption (17). We chose this strain specifically because of its tractable metabolic
				network and its versatility to a wide range of pHs and temperatures (2). The microbe’s
				ability to grow at higher salinities also helps to decrease contamination. After being
				exposed to 0.1mT 50Hz EMFs for 5, 15, and 30 minutes, we found that ELF EMFs do not have
				statistically significant effects on the growth of <i>M. alcaliphilum 20Z<sup>R</sup></i>.
				Despite the results not supporting our hypothesis, the premise of our study is still
				important as increasing the growth of such bacteria could have drastic impacts on reducing
				greenhouse gasses in our atmosphere.
			</p>
			<p class="title is-4 is-spaced">Results</p>
			<p class="subtitle is-6 is-spaced">
				Our experiment aimed to test the feasibility of 0.1mT 50 Hz ELF EMFs on increasing the
				growth of <i>M. alcaliphilum 20Z<sup>R</sup></i>. We divided the samples into four groups,
				each containing three bottles (biological replicates). The control group was not exposed to
				the EMF, while the three experimental groups were exposed for 5 minutes, 15 minutes, or 30
				minutes, with the exposure occurring at hour 20. We quantified the concentration (and
				therefore growth) of the bacteria by measuring the optical density (OD) of the samples
				periodically over 67 hours.
				<br />
				<br />
				The growth curve, which shows the OD reading as a function of time, suggests that at the end
				of exponential phase (hour 23.5), samples exposed to the EMF for 5 minutes had an approximate
				11.99% increase in growth when compared to the control group (Figure 1). Similarly, samples exposed
				for 15 minutes had an approximate 10.98% increase in growth, and those exposed for 30 minutes
				experienced around a 1.73% increase in growth over the control (Table 1). OD readings were taken
				well into the bacteria’s stationary phase in order to examine the longer lasting effects of this
				treatment. We observed that in each sample's highest OD reading at hour 45.5, those exposed for
				5 minutes had around a 16.79% higher maximum OD as compared to the control group. Additionally,
				those exposed for 15 minutes had an approximate 8.94% higher maximum density. On the other hand,
				the group exposed for a consecutive 30-minute time period experienced a 5.45% decrease in the
				maximum OD reading. It is important to note that the slight decrease in OD of the bacteria between
				hour 18 and 20 depicts the period in which samples were taken off the shaker whilst being exposed
				to the generated field.
			</p>
			<div class="has-text-centered">
				<figure>
					<figcaption>
						<strong
							>Table 1: Percent change in growth, max OD, and growth rate compared to the control.</strong
						>
					</figcaption>
					<img src="/table1.png" alt="Image of Table 1" />
				</figure>
				<br />
				<figure>
					<figcaption>
						<strong>Figure 1: Growth curve after exposure to 0.1mT 50Hz EMF.</strong>
					</figcaption>
					<img src="/figure1.png" alt="Image of Figure 1" />
				</figure>
				<br />
			</div>
			<p>
				The growth rate, defined as the rate of change in the number of bacteria per unit of time,
				was calculated from the moment of exposure (hour 20) to the end of exponential phase (hour
				23.5). Our results show that samples exposed to the EMF for 5 minutes had a 64.59% increase
				in bacterial growth rate, while those for exposed 15 minutes had a 51.23% increase, and
				finally those exposed for 30 minutes had a 41.80% increase when compared to the control
				group (Figure 2).
			</p>
			<br />
			<div class="has-text-centered">
				<figure>
					<figcaption>
						<strong>Figure 2: Growth rate after exposure to 0.1mT 50Hz EMF.</strong>
					</figcaption>
					<img src="/figure2.png" alt="Image of Figure 2" />
				</figure>
			</div>
			<br />
			<p>
				Using the average OD values from the moment of exposure (hour 20) to the end of exponential
				phase (hour 23.5), we determined that, when analyzed against the control group, the growth
				of the experimental samples exposed for 5 minutes (t-test, p = 0.20), 15 minutes (p = 0.19),
				and 30 minutes (p = 0.49) was not statistically significantly different because the p-values
				are higher than our significance level (α = 0.016). Therefore, the null hypothesis, being
				that there is no correlation between exposure time and general growth, cannot be rejected
				and our data can only provide support for correlation between the variables being studied.
			</p>
			<br />
			<p class="title is-4 is-spaced">Discussion</p>
			<p class="subtitle is-6 is-spaced">
				Methane is considered to be one of the most effective heattrapping greenhouse gasses (1).
				With the rise in emissions from open-pit landfills, farms, and factories, environmental
				scientists are scrambling for new methods to combat the release of this chemical. This study
				examines the effects of ELF EMFs on the growth of the methanotrophic bacterium <i
					>M. alcaliphilum 20Z<sup>R</sup></i
				>
				in hopes of stimulating bacterial proliferation but ultimately found that there were no statistically
				significant impacts.
				<br />
				<br />
				To this day, there have been mixed results on the effects of ELF EMF exposure on biological systems.
				Some studies have claimed these fields accelerate cell potentials, promote healing, and reduce
				inflammation, while others have noticed its detrimental effects on both bacterial colony forming
				unit count (the number of bacterial cells in a sample viable for binary fission) and OD readings
				(18-19). Perhaps the effects are dependent solely on the type of biological organism being exposed,
				or possibly there exists a complex relationship between the duration of time and EMF intensity
				a bacterial sample can be exposed to before causing negative/harmful effects (20). The wide range
				of positive and negative results generated by the experiments cited in this manuscript make it
				difficult to identify an exact reference point. Additionally, it is not known how large a change
				in growth could theoretically be, especially for each strain of bacteria, given the fact that
				research in this area on a molecular level is still novel.
				<br />
				<br />
				As our results indicate, exposure to a 0.1mT 50Hz ELF EMF for 5, 15, and 30 minutes does not
				appear to have a significant effect on the growth rates or growth curves of methanotrophic bacteria.
				However, this could very well be due to the low statistical power of this experiment, therefore
				making it important to continue experimentation under identical conditions. Some factors and
				limitations that could have influenced the results of this study was the fact that the ELF EMF
				exposure system was designed and developed in-house, meaning that small imperfections in the
				wounding of the wire may have had miniscule impacts on the perfect uniformity of the field created.
				<br />
				<br />
				The reason for choosing our specific parameters as outlined in our hypothesis was because of
				prior research done in the field with similar frequencies and intensities that demonstrated that
				exposure for 10 minutes could lead to positive effects on bacterial growth, enzyme kinetics,
				and gene expression, while exposure for longer periods of time greater than 30 minutes showed
				negative effects on these attributes (21-23). Future studies to expand on this one could test
				the effects of a larger range of field densities (0.1mT–5mT) and a larger range of exposure times
				(5–60 minutes). In short, similar and altered conditions with a larger sample size will help
				paint a better, more solid picture of the effects of ELF EMF exposure on methanotrophs and gain
				a stronger understanding of which variables could lead to the most positive effects.
				<br />
				<br />
				Although the results generated by this experiment supported the null hypothesis, the basis for
				this study is still important because successfully increasing the growth rates of methane-consuming
				bacteria can lead to an increase in methane oxidation rates and thus has the potential to reduce
				the detrimental methane concentration in Earth’s atmosphere.
			</p>
			<p class="title is-4 is-spaced">Materials and Methods</p>
			<p class="title is-6">Construction of the Helmholtz Coil</p>
			<p class="subtitle is-6 is-spaced">
				A Helmholtz coil consists of two identical magnetic coils facing parallel to each other. The
				radius of each coil matches the distance separating the two coils. When current passes
				through both coils, it generates a uniform magnetic field. In this particular experiment,
				each coil had a radius of 50mm, each composed of 25 wounds of 14 American Wire Gauge
				insulated copper magnetic wire. One individual coil was attached to a power supply (Lavolta
				BPS-305) running at ~535mA and 0.05V, while the other to a waveform amplifier (Sony CMX-E22)
				and a signal generator (FG-100 DDS) (Figure 3). The intersection of the magnetic field
				produced by each coil summates to form a sinusoidal wave with a direct current offset.
			</p>
			<div class="has-text-centered">
				<figure>
					<figcaption style="margin-bottom:10px;">
						<strong
							>Figure 3: The extremely low-frequency electromagnetic field generator with each
							component labeled.
						</strong>
					</figcaption>
					<img src="/figure3.png" alt="Image of Figure 3" />
				</figure>
			</div>
			<br />
			<p class="title is-6">Preparation of Liquid Medium</p>
			<p class="subtitle is-6 is-spaced">
				The bacterium <i>M. alcaliphilum 20Z<sup>R</sup></i> was grown in a nitrate mineral salts
				(NMS) medium which contained 1M potassium nitrate (KNO<sub>4</sub>), 0.2M magnesium sulfate
				(MgSO<sub>4</sub>) x 7•H<sub>2</sub>O, 0.02M calcium dichloride (CaCl<sub>2</sub>) x 2•H<sub
					>2</sub
				>O, and distilled, deionized water (24). The medium was supplemented with 1mL/L trace
				solution, 20mL/L phosphate solution, and 40mL/L carbonate solution. The trace solution
				contained 5M ethylenediaminetetraacetic acid disodium salt (Na<sub>2</sub>EDTA), 2M ferrous
				sulfate (FeSO<sub>4</sub>) x 7•H<sub>2</sub>O, 0.3M zinc sulfate (ZnSO<sub>4</sub>) x 7•H<sub
					>2</sub
				>O, 0.03M manganese(II) chloride (MnCl<sub>2</sub>) x 4•H<sub>2</sub>O, 0.2M cobalt chloride
				(CoCl<sub>2</sub>) x 6•H<sub>2</sub>O, 0.6M copper sulfate (CuSO<sub>4</sub>) x 5•H<sub
					>2</sub
				>O, 0.05M nickel chloride (NiCl<sub>2</sub>) x 6•H<sub>2</sub>O, 0.05M sodium molybdate
				(Na2MoO4) x 2•H<sub>2</sub>O, and 0.03M boric acid (H<sub>3</sub>BO<sub>3</sub>). The
				phosphate solution contained 5.44M potassium dihydrogen phosphate (KH<sub>2</sub>PO<sub
					>4</sub
				>) and 5.68M disodium hydrogen phosphate (Na<sub>2</sub>HPO<sub>4</sub>) while the carbonate
				solution contained 75.6M sodium bicarbonate (NaHCO<sub>3</sub>), and 10.5M sodium carbonate
				(Na<sub>2</sub>CO<sub>3</sub>).
			</p>
			<p class="title is-6">Preparation of Liquid Culture</p>
			<p class="subtitle is-6 is-spaced">
				Twelve 100mL bottles were autoclaved at 121°C for 45 minutes. In order to increase the pH
				and use it as a buffer, 3mL of phosphate and 6mL of carbonate solutions were then added into
				an already prepped bottle containing 150mL of NMS medium. Once mixed, 25mL of this solution
				was then inserted into three bottles for three biological replicate samples. Cultures were
				inoculated with bacteria grown from a frozen stock on a petri dish containing NMS agar. 50cm<sup
					>3</sup
				>
				of gaseous methane via needle and syringe was introduced into each bottle. The prepared containers
				were then placed in the 30°C shaker overnight at 200rpm. Once again, 3mL of phosphate and 6mL
				of carbonate were then each added into two new 150mL bottles of NMS medium and then divided evenly
				(25mL each) into the 12 previously autoclaved 100mL bottles. They were then labeled based on
				their associated biological replicates and time of exposure (control or 0 minutes, 5 minutes,
				15 minutes, or 30 minutes). OD readings were taken of the three initial biological replicate
				bottles at 600nm. All 12 cultures were then split to OD = 0.024. It was determined that 0.67mL
				of biological replicate 1, 0.66mL of biological replicate 2, and 0.75mL of biological replicate
				3 was needed to obtain these concentrations. After inoculation of the bacteria into the bottles,
				50cm<sup>3</sup> of methane gas was then added to each of the 12 bottles via needle and syringe
				and then placed in the 30°C shaker overnight until it reached an OD of 0.50 the next morning.
			</p>
			<p class="title is-6">ELF EMF Exposure</p>
			<p class="subtitle is-6 is-spaced">
				Each sample was then exposed to the ELF EMF for the specified duration of time just before
				reaching the exponential phase (hour 20). In order to maintain a controlled experiment, all
				bottles were taken off the shaker for the same amount of time, meaning those not facing
				exposure at the moment were placed on the side away from the generating source.
			</p>
			<p class="title is-6">Optical Density Readings</p>
			<p class="subtitle is-6 is-spaced">
				OD readings were taken every 1–2 hours apart until hour 67. A needle was inserted into the
				lid of each bottle and 1mL of solution was extracted. The liquid was then placed in a
				spectrophotometer (Jenway 6320D) at 600nm and values were recorded on a table.
			</p>
			<p class="title is-6">Data Analysis</p>
			<p class="subtitle is-6 is-spaced">
				The average values for the three biological replicates were taken and used to calculate
				growth, maximum optical density, and growth rate along with the respective percent change.
				Growth is simply the average OD values recorded at each period in time. By subtracting the
				OD value of the control at the end of exponential phase (hour 23.5) from each of the exposed
				samples, dividing it by the control, and then multiplying by 100, the percent difference can
				be seen. A similar process was done for maximum OD except at hour 45.5. Growth rate for each
				condition was calculated from the moment of exposure at hour 20 to the end of exponential
				phase at hour 23.5 using the exponential growth equation Nt = No (1 + r)t , where Nt is the
				final OD value, No is the initial OD value, r as the unknown rate constant, and t as time.
				The percent difference equation was applied to the newfound r values in an identical fashion
				to the growth and optical density calculations. The built-in Microsoft Excel one-tailed
				t-test was used to calculate significance between the control and exposed samples. To
				account for multiple comparisons a Bonferroni corrected α-level of 0.016 was used.
			</p>
			<p class="title is-4 is-spaced">Acknowledgements</p>
			<p class="subtitle is-6 is-spaced">
				We would like to acknowledge Arsen Musayelyan for sharing his knowledge on electronics and
				Sam Fatehmanesh for his generosity in lending the power supply. It is also important to note
				the flexibility of the rest of the Chu family and their contributions to planning the
				logistics of conducting research outside of Los Angeles.
			</p>
			<p class="title is-4 is-spaced">References</p>
			<div class="content">
				<ol type="1">
					<li>
						Borunda, Alejandra. “Methane, explained.” National Geographic, 23 January 2019,
						www.nationalgeographic. com/environment/article/methane. Accessed 3 May 2021.
					</li>
					<li>
						Akberdin, I. R., et al. “Methane utilization in <i
							>Methylomicrobium alcaliphilum 20Z<sup>R</sup></i
						>: A systems approach.” Scientific Reports, vol. 8, no. 2512, 2018
						doi:10.1038/s41598-018-20574-z.
					</li>
					<li>
						Park, Seon-yeong, et al. “Application and development of methanotrophs in environmental
						engineering”. Journal of Material Cycles Waste Management 21, 415–422, 2019.
						doi:10.1007/s10163-018-00826-w.
					</li>
					<li>
						Wang, S., et al. “Enrichment of denitrifying methanotrophic bacteria from Taihu
						sediments by a membrane biofilm bioreactor at ambient temperature”. Environmental
						Science Pollution Research 23, 5627–5634, 2016. doi:10.1007/s11356-015-5509-0.
					</li>
					<li>
						Iguchi, Hiroyuki et al. “Stimulation of methanotrophic growth in cocultures by cobalamin
						excreted by rhizobia.” Applied and Environmental Microbiology vol. 77,24, 2011: 8509-15.
						doi:10.1128/AEM.05834-11.
					</li>
					<li>
						“Radiation: Electromagnetic Fields.” World Health Organization, 4 Aug. 2016,
						www.who.int/news-room/qa-detail/radiation-electromagnetic-fields. Accessed 5 March 2021.
					</li>
					<li>
						“Electromagnetic Fields.” World Health Organization,
						www.who.int/health-topics/electromagneticfields#tab=tab_1. Accessed 5 March 2021.
					</li>
					<li>
						N. M. Shupak, F. S. Prato and A. W. Thomas, "Therapeutic uses of pulsed magnetic-field
						exposure: A review," in Union Radio-Scientifique Internationale Radio Science Bulletin,
						vol. 2003, no. 307, pp. 9-32, Dec. 2003, doi:10.23919/URSIRSB.2003.7909506.
					</li>
					<li>
						Milgram, Joshua et al. “The effect of short, high intensity magnetic field pulses on the
						healing of skin wounds in rats.” Bioelectromagnetics vol. 25,4, 2004: 271-7.
						doi:10.1002/bem.10194.
					</li>
					<li>
						Goudarzi, Iran et al. “Pulsed electromagnetic fields accelerate wound healing in the
						skin of diabetic rats.” Bioelectromagnetics vol. 31,4, 2010: 318-23. doi:10.1002/
						bem.20567
					</li>
					<li>
						Bohn, Wolfgang et al. "The effects of the “physical BEMER® vascular therapy”, a method
						for the physical stimulation of the vasomotion of precapillary microvessels in case of
						impaired microcirculation, on sleep, pain and quality of life of patients with different
						clinical pictures on the basis of three scientifically validated scales" Journal of
						Complementary and Integrative Medicine, vol. 10, no. Supplement-English, 2013, pp.
						S5-S12. doi:10.1515/jcim2013-0037
					</li>
					<li>
						Tessaro, Lucas W.E., et al. “Bacterial Growth Rates Are Influenced by Cellular
						Characteristics of Individual Species When Immersed in Electromagnetic Fields.”
						Microbiological Research, vol. 172, 2015, pp. 26–33., doi:10.1016/j.micres.2014.12.008.
					</li>
					<li>
						Chen, Yu, et al. “Evaluation of the Extremely-LowFrequency Electromagnetic Field
						(Elf-Emf) on Growth of Bacteria Escherichia Coli.” Biology, Engineering and Medicine,
						vol. 4, no. 2, 2019, doi:10.15761/bem.1000169.
					</li>
					<li>
						R. de Seze et al. “Generation of extremely-low frequency magnetic fields with standard
						available commercial equipment: Implications for experimental bioelectromagnetics work”,
						Bioelectrochemistry and Bioenergetics, Volume 35, Issues 1–2, 1994, Pages 127- 131, ISSN
						0302-4598, doi:10.1016/0302-4598(94)87023- 3.
					</li>
					<li>
						E. J. Garcia et al. "ELF magnetic fields generator, variable in intensity and frequency
						for biological applications," 2005 2nd International Conference on Electrical and
						Electronics Engineering, 2005, pp. 185-188, doi:10.1109/ ICEEE.2005.1529604.
					</li>
					<li>
						Istiaque, Ahmed, et al. “Design and development of Extremely Low frequency (ELF) Pulsed
						Electromagnetic Field (PEMF) System for wound healing promotion”. in World Congress on
						Medical Physics and Biomedical Engineering. Heidelberg, Germany: IFMBE Proceedings.
						Springer, Mian Long; 2012:27–30.
					</li>
					<li>
						Vuilleumier, Stéphane, et al. “Genome sequence of the haloalkaliphilic methanotrophic
						bacterium
						<i>Methylomicrobiumalcaliphilum 20Z</i>.” Journal of Bacteriology. 2012;194(2):551–552.
						doi:10.1128/ JB.06392-11.
					</li>
					<li>
						Istiaque, Ahmed, et al. “Irradiation of Escherichia coli by extremely-low frequency
						(ELF) pulsed electromagnetic fields (PEMF): evaluation of bacterial survival”, Journal
						of Electromagnetic Waves and Applications, 29:1, 26-37, 2015.
						doi:10.1080/09205071.2014.974684
					</li>
					<li>
						L. Strašák, et al. “Effects of 50 Hz Magnetic Fields on the Viability of Different
						Bacterial Strains”, Electromagnetic Biology and Medicine, 24:3, 293-300, 2005.
						doi:10.1080/15368370500379715.
					</li>
					<li>
						Sudarti, et al. “Effective Dose Analysis of Extremely Low Frequency (ELF) Magnetic Field
						Exposure to Growth of S. Termophilus, L. Lactis, L. Acidophilus Bacteria.” IOP
						Conference Series: Materials Science and Engineering, vol. 432, 2018, p. 012010., 2018.
						doi:10.1088/1757- 899x/432/1/012010.
					</li>
					<li>
						Cairo, P et al. “Magnetic field exposure enhances mRNA expression of sigma 32 in E.
						coli.” Journal of Cellular Biochemistry vol. 68,1 1998: 1-7.
					</li>
					<li>
						Ahmed I., Vojisavljevic V. and Pirogova E.. Investigation of the Effect of Extremely Low
						Frequency (ELF) Pulsed Electromagnetic Field (PEMF) on Collagenase Enzyme Kinetics. doi:
						10.5220/0004239501430147 In Proceedings of the International Conference on Biomedical
						Electronics and Devices (BIODEVICES-2013), pp. 143-147 ISBN: 978-989-8565-34-1.
					</li>
					<li>
						Belyaev, Igor & Alipov, Yevgeny & Harms-Ringdahl, Mats. “Effects of Weak ELF on E. Coli
						Cells and Human Lymphocytes: Role of Genetic, Physiological, and Physical Parameters” in
						Electricity and Magnetism in Biology and Medicine, 1999, pp. 481-483.
					</li>
					<li>
						Kalyuzhnaya MG, Marina et al. “Methanotrophic Cultures.” C1 biocatalysis Lab,
						sci.sdsu.edu/kalyuzhlab/ methanotrophic-cultures/. Accessed March 16 2021.
					</li>
				</ol>
			</div>
			<p class="title is-6 is-spaced">
				Copyright: © 2022 Chu, Kalyuzhnaya, & Hamilton. All JEI articles are distributed under the
				attribution non-commercial, no derivative license (http://creativecommons.org/licenses/
				by-nc-nd/3.0/). This means that anyone is free to share, copy and distribute an unaltered
				article for non-commercial purposes provided the original author and source is credited.
			</p>
		</div>
	</div>
	<div class="hero-foot">
		<div class="container has-text-centered mb-3 is-size-3">
			<a href="https://github.com/cchuster" target="_blank" style="font-size: 4vh;"
				><Icon icon="mdi:github" /></a
			>
			<a href="https://www.linkedin.com/in/connerchu" target="_blank" style="font-size: 4vh;"
				><Icon icon="mdi:linkedin" /></a
			>
			<a
				href="javascript:void(0);"
				style="font-size: 4vh;"
				use:tippy={{ content: tooltipContent, placement: 'top', hideOnClick: false }}
				on:click={copyEmail}
			>
				<Icon icon="material-symbols:mail" />
			</a>
		</div>
	</div>
</section>
